AWSTemplateFormatVersion: "2010-09-09"

Transform:
 - AWS::Serverless-2016-10-31

Description: CsvToDynamo
Resources:
    LambdaCsvToDynamo:
        Type: AWS::Serverless::Function
        Properties:
          Handler: csv_to_dynamodb.handler
          Runtime: python3.6
          CodeUri: package/
          Timeout: 10
          Policies:
           - DynamoDBCrudPolicy:
              TableName: pets
           - S3CrudPolicy:
              BucketName: csv-dynamodb-lambda